CC = cc
CFLAGS = -std=c99 -pedantic -Wall
OBJECTS = main.o
all: main.c problem5char.c problem5lines.c problem5words.c
	gcc -o main main.c problem5char.c  problem5lines.c problem5words.c
	./main
		
	
	
